name: build C library
on: pull_request
jobs:
    Run-asn1c:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install packages
              run: |
                sudo apt get update
                sudo apt install asn1c meson crossbuild-essential-riscv64
            - name: Build
              run: |
                cd lib
                meson setup build64 --cross-file riscv64-unknown-elf
                cd build64
                ninja
